// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcxxnsasikxvnqlluhgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjeHhuc2FzaWt4dm5xbGx1aGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDA1NjksImV4cCI6MjA2NDM3NjU2OX0.2w3wQuhsMhllt9MDD5jexSmrI1SVaij0NQ90mXbiL_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);